server:
  port: 18080
spring:
  datasource:
    druid:
      db-type: mysql
      driver-class-name: com.mysql.cj.jdbc.Driver
      #url: jdbc:mysql://127.0.0.1:3306/DEVICE?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      url: jdbc:mysql://47.93.30.9:3306/DEVICE?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
      username: spider
      password: Spider#3340
      # 连接池的配置信息
      # 初始化大小，最小，最大
      initial-size: 20
      min-idle: 20
      max-active: 100
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      test-on-borrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙(关闭wall)
      filters: stat,wall,log4j2
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      # 配置DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      # 配置DruidStatViewServlet
      #是否启用StatViewServlet（监控页面）默认值为false（考虑到安全问题默认并未启动，如需启用建议设置密码或白名单以保障安全）
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        # IP白名单(没有配置或者为空，则允许所有访问)
        allow: 127.0.0.1,47.93.30.9
        # IP黑名单 (存在共同时，deny优先于allow)
        deny: 47.93.30.9
        #  禁用HTML页面上的“Reset All”功能
        reset-enable: false
        # 登录名
        login-username: admin
        # 登录密码
        login-password: 123456

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.hsmy.dataprocess.pojo

#native
#sending:
#  url: http://www.798joy.com:1080/recv
#  group_count: 10000
#  encoding: utf-8
#  timeout: 3000000
#  key: 3fa6f09b
#
#saving:
#  src_path: /Users/lahm/Desktop/data/
#  his_path: /Users/lahm/Desktop/history/

#server
sending:
  url: http://47.103.84.246/api/mc
  group_count: 10000
  encoding: utf-8
  timeout: 3000000
  key: 3fa6f09b

saving:
  src_path: /data/backup/httpd/
  his_path: /data/backup/history/

#配置日志信息
logging:
  config: classpath:logback-spring.xml
  path: /log/
  # path: /Users/eipwork/Documents
  level:
    root: error